const prefix = 'GoldenCoal/'

export const PARTICIPANT_CHANGED = prefix + 'PARTICIPANT_CHANGED';

export const VALIDATION_REQUEST = prefix + 'VALIDATION_REQUEST';
export const VALIDATION_ACCEPTED = prefix + 'VALIDATION_ACCEPTED';
export const VALIDATION_SUCCESS = prefix + 'VALIDATION_SUCCESS';
export const VALIDATION_FAILURE = prefix + 'VALIDATION_FAILURE';

export const ALLOW_PARTICIPATION = prefix + 'ALLOW_PARTICIPATION';
export const DISALLOW_PARTICIPATION = prefix + 'DISALLOW_PARTICIPATION';

export const PARTICIPATION_BEFORE = prefix + 'PARTICIPATION_BEFORE';
export const PARTICIPATION_SUCCESS = prefix + 'PARTICIPATION_SUCCESS';
export const PARTICIPATION_FAILURE = prefix + 'PARTICIPATION_FAILURE';

export const CONTACT_REQUEST_BEFORE = prefix + 'CONTACT_REQUEST_BEFORE';
export const CONTACT_REQUEST_SUCCESS = prefix + 'CONTACT_REQUEST_SUCCESS';
export const CONTACT_REQUEST_FAILURE = prefix + 'CONTACT_REQUEST_FAILURE';

export const INCREMENT_STEP = prefix + 'INCREMENT_STEP';
export const DECREMENT_STEP = prefix + 'DECREMENT_STEP';

export const PHARMACY_CHANGED = prefix + 'PHARMACY_CHANGED';
export const POSITION_CHANGED = prefix + 'POSITION_CHANGED';
export const REGION_CHANGED = prefix + 'REGION_CHANGED';
export const PARTICIPATE_REGION_CHANGED = prefix + 'PARTICIPATE_REGION_CHANGED';
export const WINNER_REGION_CHANGED = prefix + 'WINNER_REGION_CHANGED';

export const CONTACT_CHANGED = prefix + 'CONTACT_CHANGED';

export const PARTICIPANT_SEARCH_CHANGED = prefix + 'PARTICIPANT_SEARCH_CHANGED';
export const WINNER_SEARCH_CHANGED = prefix + 'WINNER_SEARCH_CHANGED';
export const WINNER_CONTACT_CHANGED = prefix + 'WINNER_CONTACT_CHANGED';

export const WINNER_ENABLE_CONTACT_FORM = prefix + 'WINNER_ENABLE_CONTACT_FORM';
export const WINNER_DISABLE_CONTACT_FORM = prefix + 'WINNER_DISABLE_CONTACT_FORM';

export const WINNER_CONTACT_REQUEST = prefix + 'WINNER_CONTACT_REQUEST';
export const WINNER_CONTACT_ACCEPTED = prefix + 'WINNER_CONTACT_ACCEPTED';
export const WINNER_CONTACT_BEFORE = prefix + 'WINNER_CONTACT_BEFORE';
export const WINNER_CONTACT_SUCCESS = prefix + 'WINNER_CONTACT_SUCCESS';
export const WINNER_CONTACT_FAILURE = prefix + 'WINNER_CONTACT_FAILURE';

export const FETCH_PARTICIPANTS_REQUEST = prefix + 'FETCH_PARTICIPANTS_REQUEST';
export const FETCH_PARTICIPANTS_ACCEPTED = prefix + 'FETCH_PARTICIPANTS_ACCEPTED';
export const FETCH_PARTICIPANTS_BEFORE = prefix + 'FETCH_PARTICIPANTS_BEFORE';
export const FETCH_PARTICIPANTS_SUCCESS = prefix + 'FETCH_PARTICIPANTS_SUCCESS';
export const FETCH_PARTICIPANTS_FAILURE = prefix + 'FETCH_PARTICIPANTS_FAILURE';

export const FETCH_WINNERS_REQUEST = prefix + 'FETCH_WINNERS_REQUEST';
export const FETCH_WINNERS_ACCEPTED = prefix + 'FETCH_WINNERS_ACCEPTED';
export const FETCH_WINNERS_BEFORE = prefix + 'FETCH_WINNERS_BEFORE';
export const FETCH_WINNERS_SUCCESS = prefix + 'FETCH_WINNERS_SUCCESS';
export const FETCH_WINNERS_FAILURE = prefix + 'FETCH_WINNERS_FAILURE';
