const prefix = 'WhiteCoal/'

export const PARTICIPANT_CHANGED = prefix + 'PARTICIPANT_CHANGED';
export const PARTICIPATE_REGION_CHANGED = prefix + 'PARTICIPATE_REGION_CHANGED';

export const VALIDATION_REQUEST = prefix + 'VALIDATION_REQUEST';
export const VALIDATION_ACCEPTED = prefix + 'VALIDATION_ACCEPTED';
export const VALIDATION_SUCCESS = prefix + 'VALIDATION_SUCCESS';
export const VALIDATION_FAILURE = prefix + 'VALIDATION_FAILURE';

export const ALLOW_PARTICIPATION = prefix + 'ALLOW_PARTICIPATION';
export const DISALLOW_PARTICIPATION = prefix + 'DISALLOW_PARTICIPATION';

export const FETCH_REGION_BEFORE = prefix + 'FETCH_REGION_BEFORE';
export const FETCH_REGION_SUCCESS = prefix + 'FETCH_REGION_SUCCESS';
export const FETCH_REGION_FAILURE = prefix + 'FETCH_REGION_FAILURE';

export const FETCH_PHARMACY_TYPE_BEFORE = prefix + 'FETCH_PHARMACY_TYPE_BEFORE';
export const FETCH_PHARMACY_TYPE_SUCCESS = prefix + 'FETCH_PHARMACY_TYPE_SUCCESS';
export const FETCH_PHARMACY_TYPE_FAILURE = prefix + 'FETCH_PHARMACY_TYPE_FAILURE';

export const FETCH_POSITION_BEFORE = prefix + 'FETCH_POSITION_BEFORE';
export const FETCH_POSITION_SUCCESS = prefix + 'FETCH_POSITION_SUCCESS';
export const FETCH_POSITION_FAILURE = prefix + 'FETCH_POSITION_FAILURE';

export const PARTICIPATION_BEFORE = prefix + 'PARTICIPATION_BEFORE';
export const PARTICIPATION_SUCCESS = prefix + 'PARTICIPATION_SUCCESS';
export const PARTICIPATION_FAILURE = prefix + 'PARTICIPATION_FAILURE';

export const INCREMENT_STEP = prefix + 'INCREMENT_STEP';
export const DECREMENT_STEP = prefix + 'DECREMENT_STEP';

export const PHARMACY_CHANGED = prefix + 'PHARMACY_CHANGED';
export const POSITION_CHANGED = prefix + 'POSITION_CHANGED';
export const REGION_CHANGED = prefix + 'REGION_CHANGED';

export const PARTICIPANT_SEARCH_CHANGED = prefix + 'PARTICIPANT_SEARCH_CHANGED';

export const FETCH_PARTICIPANTS_REQUEST = prefix + 'FETCH_PARTICIPANTS_REQUEST';
export const FETCH_PARTICIPANTS_ACCEPTED = prefix + 'FETCH_PARTICIPANTS_ACCEPTED';
export const FETCH_PARTICIPANTS_BEFORE = prefix + 'FETCH_PARTICIPANTS_BEFORE';
export const FETCH_PARTICIPANTS_SUCCESS = prefix + 'FETCH_PARTICIPANTS_SUCCESS';
export const FETCH_PARTICIPANTS_FAILURE = prefix + 'FETCH_PARTICIPANTS_FAILURE';

export const FETCH_WINNERS_REQUEST = prefix + 'FETCH_WINNERS_REQUEST';
export const FETCH_WINNERS_ACCEPTED = prefix + 'FETCH_WINNERS_ACCEPTED';

export const PARTICIPANT_CODE_CHANGED = prefix + 'PARTICIPANT_CODE_CHANGED';
export const PARTICIPANT_CODE_CHECK = prefix + 'PARTICIPANT_CODE_CHECK';

export const PARTICIPATION_ACCESS_DENIED = prefix + 'PARTICIPATION_ACCESS_DENIED';
export const PARTICIPATION_ACCESS_GRANTED = prefix + 'PARTICIPATION_ACCESS_GRANTED';
