parameters:
    database_host: psql-master
    database_port: 5432
    database_name: golden-coal
    database_user: postgres
    database_password: 12345
    database_driver: pdo_pgsql
    mailer_transport: smtp
    mailer_host: mail.ukraine.com.ua
    mailer_user: bestsorbent@xn--90acdg3ada5d5fscf.com
    mailer_password: carbowhite2017
    secret: 12345
    spa_version: 1.0.0
    managers:
        - gram7gram@gmail.com
