security:
    encoders:
        Gram\UserBundle\Entity\User:
            id: gram.security_password_encoder

    providers:
        fos.user_provider:
            id: fos_user.user_provider.username

    firewalls:
        entry:
            pattern: ^/$
            anonymous: true

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_v1:
            pattern: ^/api/v1/
            anonymous: true

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1, role: IS_AUTHENTICATED_ANONYMOUSLY }
