services:

    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]

    kernel.listener.slack_error:
        class: Gram\EventBundle\Listener\SlackExceptionListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 5000 }
            - { name: kernel.event_listener, event: kernel.response, method: onBadResponse, priority: 4000 }