api_v1_participant_gets:
    path: /events/{id}/participants
    methods: [GET]
    defaults:
        _controller: GramEventBundle:ParticipantREST:gets
    requirements:
        id: \d+

api_v1_participant_post:
    path: /events/{id}/participants
    methods: POST
    defaults:
        _controller: GramEventBundle:ParticipantREST:post
    requirements:
        id: \d+


api_v1_export_participants_gets:
    path: /export/participants
    methods: GET
    defaults:
        _controller: GramEventBundle:Export:gets