const prefix = 'GoldenCoal/'

export const PARTICIPANT_CHANGED = prefix + 'PARTICIPANT_CHANGED';

export const VALIDATION_REQUEST = prefix + 'VALIDATION_REQUEST';
export const VALIDATION_ACCEPTED = prefix + 'VALIDATION_ACCEPTED';
export const VALIDATION_SUCCESS = prefix + 'VALIDATION_SUCCESS';
export const VALIDATION_FAILURE = prefix + 'VALIDATION_FAILURE';

export const ALLOW_PARTICIPATION = prefix + 'ALLOW_PARTICIPATION';
export const DISALLOW_PARTICIPATION = prefix + 'DISALLOW_PARTICIPATION';

export const PARTICIPATION_BEFORE = prefix + 'PARTICIPATION_BEFORE';
export const PARTICIPATION_SUCCESS = prefix + 'PARTICIPATION_SUCCESS';
export const PARTICIPATION_FAILURE = prefix + 'PARTICIPATION_FAILURE';

export const GEOCODER_FETCHING = prefix + 'GEOCODER_FETCHING';
export const GEOCODER_FETCH_SUCCESS = prefix + 'GEOCODER_FETCH_SUCCESS';
export const GEOCODER_FETCH_FAILURE = prefix + 'GEOCODER_FETCH_FAILURE';

export const GEOCODER_ADDRESS_SELECTED = prefix + 'GEOCODER_FETCH_FAILURE';

export const GMAP_MARKER_CHANGED = prefix + 'GMAP_MARKER_CHANGED';

export const INCREMENT_STEP = prefix + 'INCREMENT_STEP';
export const DECREMENT_STEP = prefix + 'DECREMENT_STEP';

export const PHARMACY_CHANGED = prefix + 'PHARMACY_CHANGED';
export const POSITION_CHANGED = prefix + 'POSITION_CHANGEDA';
export const REGION_CHANGED = prefix + 'REGION_CHANGED';
