api_v1_participant:
    resource: routing/participant.yml
    prefix: /api/v1

api_v1_winner:
    resource: routing/winner.yml
    prefix: /api/v1

api_v1_position:
    resource: routing/position.yml
    prefix: /api/v1

api_v1_pharmacy_type:
    resource: routing/pharmacy_type.yml
    prefix: /api/v1

api_v1_region:
    resource: routing/region.yml
    prefix: /api/v1

api_v1_contact:
    resource: routing/contact.yml
    prefix: /api/v1

api_v1_winner_contact:
    resource: routing/winner_contact.yml
    prefix: /api/v1

api_v1_pharmacy:
    resource: routing/pharmacy.yml
    prefix: /api/v1

api_v1_winner_pharmacy:
    resource: routing/winner_pharmacy.yml
    prefix: /api/v1

api_v1_pharmacy_participant:
    resource: routing/pharmacy_participant.yml
    prefix: /api/v1

index:
    path: /
    defaults:
        _controller: GramEventBundle:Sitemap:index

contact_index:
    path: /events/{code}/contact
    defaults:
        _controller: GramEventBundle:Sitemap:contact

about_index:
    path: /events/{code}/about
    defaults:
        _controller: GramEventBundle:Sitemap:about

register_index:
    path: /events/{code}/register
    defaults:
        _controller: GramEventBundle:Sitemap:register

participant_index:
    path: /events/{code}/participants
    defaults:
        _controller: GramEventBundle:Sitemap:participants

winner_index:
    path: /events/{code}/winners
    defaults:
        _controller: GramEventBundle:Sitemap:winner

event_index:
    path: /events/{code}
    defaults:
        _controller: GramEventBundle:Sitemap:event