services:

  event.participant_service:
      class: Gram\EventBundle\Service\ParticipantService
      arguments: ['@service_container']

  event.winner_service:
      class: Gram\EventBundle\Service\WinnerService
      arguments: ['@service_container']

  event.region_service:
      class: Gram\EventBundle\Service\RegionService
      arguments: ['@service_container']

  event.position_service:
      class: Gram\EventBundle\Service\PositionService
      arguments: ['@service_container']

  event.pharmacy_type_service:
      class: Gram\EventBundle\Service\PharmacyTypeService
      arguments: ['@service_container']

  event.contact_manager_service:
      class: Gram\EventBundle\Service\ContactService
      arguments: ['@service_container']

  event.pharmacy_service:
      class: Gram\EventBundle\Service\PharmacyService
      arguments: ['@service_container']